"""Markdown Pull Request Review Comment Formatter.
Renders rich, structured Markdown reports for Pull Request review comments with HTML marker headers.
"""

from typing import Dict, Any, List, Optional
from engine.regression.selective_selector import SelectionResult
from engine.cicd.quality_gate import QualityGateResult


class PRCommenter:
    """Formats Markdown comments for GitHub PR review summary posting."""

    MARKER = "<!-- ASTRA_REPORT -->"

    @staticmethod
    def format_pr_comment(
        quality_gate: QualityGateResult,
        selection_result: Optional[SelectionResult] = None,
        impacted_endpoints: Optional[List[Dict[str, Any]]] = None,
        failures: Optional[List[Dict[str, Any]]] = None,
        flaky_warnings: Optional[List[str]] = None,
        astra_dashboard_url: str = "https://astra.dev/defects",
    ) -> str:
        """Renders GitHub PR Markdown summary body."""
        lines = []

        # 1. Header & Quality Gate Status Badge
        status_badge = PRCommenter._get_status_badge(quality_gate.status)
        lines.append(f"# {status_badge} ASTRA Quality Gate Report")
        lines.append("")
        lines.append(f"**Gate Status:** `{quality_gate.status}` | **Blocking:** `{'Yes' if quality_gate.blocking else 'No'}`")
        lines.append("")

        # 2. Selective Execution Metrics Table
        if selection_result:
          lines.append("### 📊 Tiered Selective Regression Summary")
          lines.append("")
          lines.append("| Metric | Count / Value |")
          lines.append("|:---|:---|")
          lines.append(f"| **Total Suite Tests** | `{selection_result.total_suite_tests}` |")
          lines.append(f"| **Tier 1 Targeted (PR Executed)** | `{selection_result.selected_tier1_count}` ⚡ |")
          lines.append(f"| **Tier 2 Deferred (Scheduled Nightly)** | `{selection_result.deferred_tier2_count}` ⏳ |")
          lines.append(f"| **Execution Reduction** | **-{selection_result.test_reduction_percent:.1f}%** |")
          lines.append(f"| **Estimated Time Saved** | **{(selection_result.estimated_time_avoided_ms / 1000):.1f}s** |")
          lines.append(f"| **Reachability Confidence** | `{selection_result.impact_confidence * 100:.0f}%` |")
          lines.append("")

        # 3. Safety Gate Warnings
        if selection_result and selection_result.safety_expansion_triggered:
            lines.append("> ⚠️ **Safety Expansion Triggered**: Conservative expansion was activated due to schema migration or global utility modifications. ZERO false negatives axiom enforced.")
            lines.append("")

        # 4. Reachable API Endpoints
        if impacted_endpoints and len(impacted_endpoints) > 0:
            lines.append("### 🎯 Reachable API Endpoints")
            lines.append("")
            for ep in impacted_endpoints[:5]:
                method = ep.get("method", "GET")
                path = ep.get("path", "/")
                dist = ep.get("impact_distance", 0)
                conf = ep.get("confidence_score", 1.0)
                lines.append(f"- `{method} {path}` (distance: `{dist}`, confidence: `{conf * 100:.0f}%`)")
            if len(impacted_endpoints) > 5:
                lines.append(f"- *...and {len(impacted_endpoints) - 5} more endpoints*")
            lines.append("")

        # 5. Failures & Root Cause Callouts
        if failures and len(failures) > 0:
            lines.append("### 🔴 Defect Diagnostics & Root Causes")
            lines.append("")
            for f in failures[:3]:
                tc_name = f.get("test_name", "Test Failure")
                category = f.get("category", "DEFECT")
                summary = f.get("summary", "Assertion or HTTP failure")
                lines.append(f"#### `{tc_name}` — **{category}**")
                lines.append(f"```text\n{summary}\n```")
                lines.append("")
            lines.append(f"[🔎 Inspect Full Root Cause Traces in ASTRA Dashboard]({astra_dashboard_url})")
            lines.append("")

        # 6. Flakiness & Quarantine Alerts
        if flaky_warnings and len(flaky_warnings) > 0:
            lines.append("### ⚡ Flakiness Alerts")
            for fw in flaky_warnings:
                lines.append(f"- {fw}")
            lines.append("")

        lines.append("---")
        lines.append("*Automated Quality Gate generated by [ASTRA Software Quality Platform](https://astra.dev)*")

        return "\n".join(lines)

    @staticmethod
    def _get_status_badge(status: str) -> str:
        if status == "PASS":
            return "🟢"
        elif status == "FAIL":
            return "🔴"
        elif status == "SAFETY_EXPANDED":
            return "🟡"
        elif status == "ERROR":
            return "❌"
        return "⚪"
